curl.exe -L -o public/logos/telkomsel.svg https://upload.wikimedia.org/wikipedia/commons/b/bc/Telkomsel_2021_icon.svg
curl.exe -L -o public/logos/indosat.svg https://upload.wikimedia.org/wikipedia/commons/e/ec/Indosat_Ooredoo_Hutchison_logo.svg
curl.exe -L -o public/logos/xl.svg https://upload.wikimedia.org/wikipedia/commons/f/f6/XL_logo_2016.svg
curl.exe -L -o public/logos/smartfren.svg "https://upload.wikimedia.org/wikipedia/commons/a/a2/Smartfren_Logo_%282024%29.svg"
curl.exe -L -o public/logos/tvri.svg https://upload.wikimedia.org/wikipedia/commons/8/87/TVRI_logo_2019.svg
curl.exe -L -o public/logos/rcti.svg https://upload.wikimedia.org/wikipedia/commons/6/6f/Logo_RCTI.svg
curl.exe -L -o public/logos/sctv.svg "https://upload.wikimedia.org/wikipedia/commons/0/07/SCTV_logo_%282005-present%2C_transparent-colored%29.svg"
curl.exe -L -o public/logos/indosiar.svg https://upload.wikimedia.org/wikipedia/commons/a/af/Indosiar_2014_logo.svg
curl.exe -L -o public/logos/transtv.svg https://upload.wikimedia.org/wikipedia/commons/b/b8/Trans_TV_2013_logo.svg
curl.exe -L -o public/logos/metrotv.svg https://upload.wikimedia.org/wikipedia/commons/4/41/MetroTV_2010.svg
curl.exe -L -o public/logos/antv.svg https://upload.wikimedia.org/wikipedia/commons/5/53/Logo_antv_2009.svg
curl.exe -L -o public/logos/rtv.svg https://upload.wikimedia.org/wikipedia/commons/7/7b/RTV_logo_2014.svg
